# Generated by Django 4.2.7 on 2023-11-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product_type',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
