# Generated by Django 4.2.7 on 2023-11-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_stock_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product_type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
